version: 0.0
os: linux
files:
  - source: /configdemo.php
    destination: /var/www/html/demo/
hooks:
  BeforeInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
